export const environment = {
    production: true,
    API_KEY: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYjRhMzlkYzdhOWUyMDE2YzkzOTJjNjI5ZjlkZThmMiIsIm5iZiI6MTcyNzcxNzcwNS4yNjE0ODksInN1YiI6IjY2ZmFkZjQ4ODA3Y2Q1MWMxN2YxOTlmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wdGLNWZeFrjUn7MS9HCGubb2oooDyQH6CLiHkcmFHoI'
};
